### ISSUE TITLE
Vấn đề về thiết kế các module của sản phẩm

### ISSUE THREAD

**Issue by chirikatori** [96ers/summerizIT#4]

**Comment by chirikatori** [comment]
![Screenshot from 2024-03-14 10-45-52](https://github.com/96ers/Eng-to-Vie-Summarizer/assets/128948099/40388286-0c8e-4ce3-ac1d-7e809a3e0635)
bản thiết kế ban đầu về use case chung

**Comment by chirikatori** [comment]
@96ers/project-software

**Comment by XuanNguyen-UET** [comment]
note: ô để ngta nhập văn bản bằng bàn phím, hoặc chức năng cho paste văn bản 
(Lưu ý: Giới hạn 2000 ký tự )
- có word count, error message 
- lưu ý trong văn bản nhập vào có thể có cả tiếng việt, tiếng anh
- Đầu ra: + có tuỳ chọn với văn bản đầu ra 
	- dịch văn bản sang tiếng việt
	- copy văn bản
- Xây dựng log_in, log_out

**Comment by chirikatori** [comment]
Yêu cầu chức năng :
Cho phép người dùng chọn loại đầu vào
Cho phép người dùng số câu tóm tắt 
Cho phép người dùng hiển thị văn bản cần tóm tắt
Cho phép người dùng đăng nhập đăng xuất
Cho phép người dùng hiển thị lịch sử tóm tắt
Cho phép người dùng copy văn bản vào clipboard
@96ers/project-software

**Comment by chirikatori** [comment]
@96ers/project-software ai thiết kế xong thì đẩy lên đây luôn nhé

**Comment by XuanNguyen-UET** [comment]
Sequence diagrams cho hai yêu cầu chức năng: ![image](https://github.com/96ers/summerizIT/assets/120193184/746dddf7-9c50-4854-b813-2fb208def402)

**Comment by CoderHung** [comment]
Sequence diagram cho yêu cầu hiển thị văn bản cần tóm tắt
![1](https://github.com/96ers/summerizIT/assets/161301206/fc886263-3255-4595-b701-054bcc40725a)

**Comment by chirikatori** [comment]
![Screenshot from 2024-03-19 09-38-37](https://github.com/96ers/summerizIT/assets/128948099/9cd4aa5d-5292-40de-a036-5b6d5b58f3b7)

**Comment by chirikatori** [comment]
class Clipboard https://github.com/apokong/react-native-clipboard-plus

**Comment by chirikatori** [comment]
![423944494_1441126990156394_2949420408985171277_n](https://github.com/96ers/summerizIT/assets/128948099/c2c97167-7a3a-4884-8f41-0a438f1eaf94)
