### ISSUE TITLE
Thiết kế cơ sở dữ liệu MySQL

### ISSUE THREAD

**Issue by chirikatori** [96ers/summerizIT#6]
Thiết kế cơ sở dữ liệu lưu trữ thông tin cơ bản của người dùng bao gồm: username, email, hashed password, lịch sử các yêu cầu của người dùng và phản hồi của hệ thống.

**Comment by quangster** [comment]
thiết kế đầu tiên
![Untitled (1)](https://github.com/96ers/summerizIT/assets/111344095/09cae781-5e3e-474e-87d4-03472cb40d30)
