### ISSUE TITLE
tạo UI cho trang chủ

### ISSUE THREAD

**Issue by quangster** [96ers/summerizIT#7]
@XuanNguyen-UET tạo giao diện trang chủ cơ bản

**Comment by XuanNguyen-UET** [comment]
![image](https://github.com/96ers/summerizIT/assets/120193184/91e36e67-f7a1-4ff3-9315-1ecfc405c23f)
uploading new feature commin up
beacause of testing and adding to ensure everything will be displayed perfectly, my commit will be slow

**Comment by XuanNguyen-UET** [comment]
![image](https://github.com/96ers/summerizIT/assets/120193184/3413d5f6-234e-44c8-92f2-d95b9d65841e)
- cần tối ưu lại UI cho lựa chọn phương thức input, thiết kế responsive
- Thiết kế để hiện lịch sử thực hiện của user dưới phần tìm kiếm
